master:
  build: master
  env_file: .env.compose
  ports:
    - "80:80"
  links:
    - db
masterprocessor:
  build: master_processor
  env_file: .env.compose
  links:
    - db
worker:
  build: worker
  env_file: .env.compose
db:
  image: postgres
  env_file: .env.compose
  ports:
    - "5432:5432"
