master:
  build: build/master
  env_file: .env.production
  ports:
    - "80:80"
  links:
    - db
masterprocessor:
  build: build/master_processor
  env_file: .env.production
  links:
    - db
worker:
  build: build/worker
  env_file: .env.production
db:
  image: postgres
  env_file: .env.production
  ports:
    - "5432:5432"
