language: ruby
rvm:
  - "2.2.1"
bundler_args: --without development
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsndfile1-dev imagemagick libsox-fmt-all lame mp3val sox madplay twolame flac ffmpeg
before_script:
  - psql -c 'create database fixer_prx_org_test;' -U postgres
env:
  - DB_ENV_POSTGRES_USER=postgres
