language: ruby
rvm:
  - "2.3.1"
bundler_args: --without development
before_install:
  - sudo add-apt-repository ppa:jonathonf/ffmpeg -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsndfile1-dev libsox-fmt-all lame mp3val sox twolame
  - sudo apt-get install -qq ffmpeg
before_script:
  - psql -c 'create database fixer_prx_org_test;' -U postgres
env:
  - DB_ENV_POSTGRES_USER=postgres TRAVIS=true MAIL_FROM=fixer@prx.org MAIL_HOST=fixer.prx.dev
