# Keep all service comfiguration centralized in this file
# Any passwords/keys should still be loaded from the ENV

default: &default
  aws:
    provider: AWS
    aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
    path_style: true
  ia:
    provider: InternetArchive
    ia_access_key_id: <%= ENV['IA_ACCESS_KEY_ID'] %>
    ia_secret_access_key: <%= ENV['IA_SECRET_ACCESS_KEY'] %>
  open_calais:
    api_key: <%= ENV['OPEN_CALAIS_API_KEY'] %>
  yahoo_content_analysis:
    api_key: <%= ENV['YAHOO_CONTENT_ANALYSIS_API_KEY'] %>
    api_secret: <%= ENV['YAHOO_CONTENT_ANALYSIS_API_SECRET'] %>
  redis:
    url: <%= ENV['REDIS_PROVIDER'] %>

development:
  <<: *default

production:
  <<: *default

test:
  aws:
    provider: AWS
    aws_access_key_id: S3ABCDEFGHIJKLMNOPQRSTUVWXYZ
    aws_secret_access_key: s3a1b2c3d4e5f6g7h8i9j0a1b2c3d4e5f6g7h8i9j0a1b2c3d4e5f6g7h8i9j0
    path_style: true
  ia:
    provider: InternetArchive
    ia_access_key_id: IAABCDEFGHIJKLMNOPQRSTUVWXYZ
    ia_secret_access_key: iaa1b2c3d4e5f6g7h8i9j0a1b2c3d4e5f6g7h8i9j0a1b2c3d4e5f6g7h8i9j0
  open_calais:
    api_key: opencaliasapikey
  yahoo_content_analysis:
    api_key: yahoocontentanalysisapikey
    api_secret: yahoocontentanalysisapisecret
  redis:
    url: 'redis://localhost:6379/12'
