<% env = ENV['APP_ENV'] || ENV['RAILS_ENV'] || 'development' %>
---
concurrency: <%= ENV['WORKER_COUNT'] || 5 %>
delay: <%= ENV['SHORYUKEN_DELAY'] || 5 %>
queues:
  - [<%= env %>_fixer_update, 3]
  - [<%= env %>_fixer_p1, 4]
  - [<%= env %>_fixer_p2, 3]
  - [<%= env %>_fixer_p3, 2]
  - [<%= env %>_fixer_p4, 1]
